Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/bionic64"
  config.vm.network "private_network", ip: "192.168.10.2"

  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y apache2 libapache2-mod-php php apache2-utils
  SHELL
end
