# -*- mode: ruby -*-
# vi: set ft=ruby :

manolorg = <<-APACHE
<VirtualHost 192.168.22.22:80>
  ServerAdmin manolorg@uca.es
  ServerName manolorg.uca.es
  DocumentRoot /var/www/manolorg
  ErrorLog ${APACHE_LOG_DIR}/error_manolorg.log
  CustomLog ${APACHE_LOG_DIR}/error_manolorg.log combined

  <Directory /var/www/manolorg>
    Options -Indexes
    <IfModule mod_rewrite.c>
      RewriteEngine On
      RewriteCond %{REQUEST_FILENAME} !-f
      RewriteCond %{REQUEST_FILENAME} !-d
      RewriteRule ^/?team/(.*?)/?$ /personalWeb.php?user=$1 [L]
    </IfModule>
  </Directory>

  <Directory /var/www/manolorg/docs>
    Options Indexes
    AuthType Basic
    AuthName "Filesystem"
    AuthBasicProvider file
    AuthUserFile "/home/vagrant/passwords"
    Require user admin manolo
  </Directory>

  <Directory /var/www/manolorg/software>
    Options Indexes
    AuthType Basic
    AuthName "Filesystem"
    AuthBasicProvider file
    AuthUserFile "/home/vagrant/passwords"
    Require user admin
  </Directory>

  <IfModule mod_expires.c>
    ExpiresActive on
    ExpiresDefault "access plus 1 minute"
    ExpiresByType image/jpg "access plus 2 minutes"
    ExpiresByType image/png "access plus 2 minutes"
  </IfModule>

  <Directory /var/www/manolorg/imagenes>
    <IfModule mod_rewrite.c>
      RewriteEngine On
      RewriteCond %{REQUEST_URI} .(jpeg)$ [NC]
      RewriteCond %{REQUEST_FILENAME} !-f
      RewriteRule "^(.*).jpeg$" "$1.jpg"
    </IfModule>
  </Directory>

  Redirect permanent "/sci2s" "https://sci2s.ugr.es/"

</VirtualHost>
APACHE

def lab(number)
  return <<-APACHE
  <VirtualHost 192.168.22.22:80>
    ServerAdmin lab#{number}.manolorg@uca.es
    ServerName lab#{number}.manolorg.uca.es
    DocumentRoot /var/www/lab#{number}
    ErrorLog ${APACHE_LOG_DIR}/error_lab#{number}_manolorg.log
    CustomLog ${APACHE_LOG_DIR}/error_lab#{number}_manolorg.log combined
  
    <Directory /var/www/lab#{number}>
      Options -Indexes
    </Directory>
  </VirtualHost>
  APACHE
end

passwd = <<-PASSWD
admin:$apr1$lFrvNnRa$jWBbUXWITX24vd1Mz86lz/
manolo:$apr1$cW9gAjUM$Zf1XZBAsDcj1HJfri7Tt3.
PASSWD

pesonalWeb = <<-PHP
  <!DOCTYPE html>
  <html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Team</title>
  </head>
  <body style="min-height:100vh;display:flex;justify-content:center;align-items:center;flex-direction:column;">
  <h1>Bienvenido</h1>
  <h2><?= $_GET["user"] ?></h2>
  </body>
  </html>
<?php
$user = $_GET["user"];
PHP

def gen_index(title,body)
  return <<-HTML
  <!DOCTYPE html>
  <html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>#{title}</title>
  </head>
  <body style="min-height:100vh;display:flex;justify-content:center;align-items:center;">#{body}</body>
  </html>
  HTML
end

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.network "private_network", ip: "192.168.22.22"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "apache"
    vb.gui = false
    vb.cpus = 2
    vb.memory = 512
  end
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y apache2 php libapache2-mod-php apache2-utils
    mkdir -p /var/www/{manolorg{,/docs,/software,/imagenes},lab{1,2}}
    sed -i '/AddDefaultCharset UTF-8/s/^#//g' /etc/apache2/conf-available/charset.conf
    echo \'#{manolorg}\' > /etc/apache2/sites-available/manolorg.conf
    echo \'#{lab(1)}\' > /etc/apache2/sites-available/lab1.manolorg.conf
    echo \'#{lab(2)}\' > /etc/apache2/sites-available/lab2.manolorg.conf
    echo \'#{gen_index("Manolorg","<h1>Manolorg</h1>")}\' > /var/www/manolorg/index.html
    echo \'#{gen_index("Laboratorio 1","<h1>Laboratorio 1</h1>")}\' > /var/www/lab1/index.html
    echo \'#{gen_index("Laboratorio 2","<h1>Laboratorio 2</h1>")}\' > /var/www/lab2/index.html
    echo \'#{passwd}\' > /home/vagrant/passwords
    echo \'#{pesonalWeb}\' > /var/www/manolorg/personalWeb.php
    a2dissite 000-default.conf
    a2ensite {lab{1,2}.,}manolorg.conf
    a2enmod rewrite
    systemctl reload apache2
  SHELL
end
