# -*- mode: ruby -*-
# vi: set ft=ruby :

# iptables -P INPUT DROP
# iptables -A INPUT -m state --state NEW -p tcp --dport 80 -j ACCEPT
# iptables -A INPUT -m state --state NEW -p tcp --dport 443 -j ACCEPT
# iptables -A INPUT -m state --state NEW,ESTABLISHED -p tcp --dport 22 -j ACCEPT

crsf = <<-CONF
<VirtualHost 192.168.22.22:80>
  ServerAdmin crsf@crsf.ai
  ServerName www.crsf.ai
  DocumentRoot /var/www/crsf
  ErrorLog ${APACHE_LOG_DIR}/error_crsf.log
  CustomLog ${APACHE_LOG_DIR}/error_crsf.log combined

  <Directory /var/www/crsf>
    Options -Indexes
    <IfModule mod_rewrite.c>
      RewriteEngine On
      RewriteCond %{REQUEST_FILENAME} !-f
      RewriteCond %{REQUEST_FILENAME} !-d
      RewriteRule ^/?catalogo/(.*?)/?$ /prodList.php?id=$1 [L]
    </IfModule>
  </Directory>

  <Directory /var/www/crsf/src>
    Options +Indexes
  </Directory>

  <Proxy balancer://nodes>
    BalancerMember node01 loadfactor=1
    BalancerMember node02 loadfactor=2
    BalancerMember node03 status=H
    ProxySet lbmethod=bytraffic
  </Proxy>

  ProxyPass "/" "balancer://nodes"

</VirtualHost>
CONF

testcrsf = <<-CONF
<VirtualHost 192.168.22.22:80>
  ServerAdmin test@crsf.ai
  ServerName test.crsf.ai
  DocumentRoot /var/www/test
  ErrorLog ${APACHE_LOG_DIR}/error_crsf_test.log
  CustomLog ${APACHE_LOG_DIR}/error_crsf_test.log combined

  <Directory /var/www/test>
    Options -Indexes
  </Directory>
</VirtualHost>
CONF

admincrsf = <<-CONF
<VirtualHost 192.168.22.22:80>
  ServerAdmin admin@crsf.ai
  ServerName admin.crsf.ai
  DocumentRoot /var/www/admin
  ErrorLog ${APACHE_LOG_DIR}/error_crsf_admin.log
  CustomLog ${APACHE_LOG_DIR}/error_crsf_admin.log combined

  <Directory /var/www/admin>
    Options -Indexes
  </Directory>
</VirtualHost>
CONF

php = <<-HTML
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Catalogo</title>
  </head>
  <body style="min-height:100vh;display:flex;justify-content:center;align-items:center;flex-direction:column;">
    <h1>Producto</h1>
    <h2><?= $_GET["id"] ?></h2>
  </body>
</html>
HTML

def gen_index(title,body)
  return <<-HTML
  <!DOCTYPE html>
  <html lang="en">
  <head>
    <!--<meta charset="UTF-8">-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>#{title}</title>
  </head>
  <body style="min-height:100vh;display:flex;justify-content:center;align-items:center;flex-direction:column;">#{body}
  <p>La ñ (en mayúscula Ñ, nombre eñe, plural eñes) es la decimoquinta letra y la duodécima consonante del alfabeto español. No pertenece al alfabeto latino básico. Representa un sonido consonante sonante, nasal y palatal.</p>
  </body>
  </html>
  HTML
end

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"

  config.vm.define "vm1" do |vm1|
    vm1.vm.hostname = "vm1"
    vm1.vm.network "private_network", ip: "192.168.22.22"
    vm1.vm.provider "virtualbox" do |vb|
      vb.name = "vm1"
      vb.memory = 512
      vb.cpus = 1
      vb.gui = false
    end
    vm1.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt-get install apache2 php libapache2-mod-php apache2-utils -y
      mkdir -p /var/www/{crsf{,/src},admin,test}
      sed -i '/AddDefaultCharset UTF-8/s/^#//g' /etc/apache2/conf-available/charset.conf
      echo \'#{crsf}\' > /etc/apache2/sites-available/www.crsf.ai.conf
      echo \'#{testcrsf}\' > /etc/apache2/sites-available/test.crsf.ai.conf
      echo \'#{admincrsf}\' > /etc/apache2/sites-available/admin.crsf.ai.conf
      echo \'#{gen_index("CRSF","<h1>CRSF</h1>")}\' > /var/www/crsf/index.html
      echo \'#{gen_index("Test | CRSF","<h1>TEST</h1>")}\' > /var/www/test/index.html
      echo \'#{gen_index("Admin | CRSF","<h1>ADMIN</h1>")}\' > /var/www/admin/index.html
      echo \'#{php}\' > /var/www/crsf/prodList.php
      echo "192.168.22.23 node01\n192.168.22.24 node02\n192.168.22.25 node03" >> /etc/hosts
      a2dissite 000-default.conf
      a2ensite {www,test,admin}.crsf.ai.conf
      a2enmod rewrite
      systemctl reload apache2
    SHELL
  end

  config.vm.define "vm2" do |vm2|
    vm2.vm.hostname = "vm2"
    vm2.vm.network "private_network", ip: "192.168.22.23"
    vm2.vm.provider "virtualbox" do |vb|
      vb.name = "vm2"
      vb.memory = 512
      vb.cpus = 1
      vb.gui = false
    end
    vm2.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt-get install apache2 -y
      echo \'#{gen_index("VM2","<h1>VM2</h1>")}\' > /var/www/html/index.html
    SHELL
  end

  config.vm.define "vm3" do |vm3|
    vm3.vm.hostname = "vm3"
    vm3.vm.network "private_network", ip: "192.168.22.24"
    vm3.vm.provider "virtualbox" do |vb|
      vb.name = "vm3"
      vb.memory = 512
      vb.cpus = 1
      vb.gui = false
    end
    vm3.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt-get install apache2 -y
      echo \'#{gen_index("VM3","<h1>VM3</h1>")}\' > /var/www/html/index.html
    SHELL
  end

  config.vm.define "vm4" do |vm4|
    vm4.vm.hostname = "vm4"
    vm4.vm.network "private_network", ip: "192.168.22.25"
    vm4.vm.provider "virtualbox" do |vb|
      vb.name = "vm4"
      vb.memory = 512
      vb.cpus = 1
      vb.gui = false
    end
    vm4.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt-get install apache2 -y
      echo \'#{gen_index("VM4","<h1>VM4</h1>")}\' > /var/www/html/index.html
    SHELL
  end
end
