$script = <<-SHELL
  apt-get update
  apt-get install -y nmap
SHELL

Vagrant.configure("2") do |config|
  (1..3).each do |i|
    config.vm.define "vm#{i}" do |node|
      node.vm.hostname = "vm#{i}"
      node.vm.box = "ubuntu/bionic64"
      node.vm.network "private_network", ip: "192.168.2.10#{i}"
      node.vm.provision "shell", inline: $script
      node.vm.provider "virtualbox" do |vb|
        vb.name = "vm#{i}"
        vb.memory = 512
        vb.cpus = 1
        vb.gui = false
      end
    end
  end
end
