# -*- mode: ruby -*-
# vi: set ft=ruby :

$script = <<-SHELL
   apt-get update
   apt-get install -y traceroute
   sed -i -e "s/PasswordAuthentication no/PasswordAuthentication yes/g" /etc/ssh/sshd_config
   systemctl restart ssh
SHELL

Vagrant.configure("2") do |config|
   config.vm.box = "ubuntu/bionic64"
   config.vm.provision "shell", inline: $script

	  config.vm.define "router" do |node|
	  	node.vm.hostname = "router"
		node.vm.network "private_network", ip: "192.168.2.1"
		node.vm.network "private_network", ip: "192.168.3.1"
		node.vm.provider "virtualbox" do |vb|
			vb.name = "router"
		    vb.memory = 512
		    vb.cpus = 1
		    vb.gui = false
	  	end
	  end
   
      config.vm.define "vm1" do |node|
         node.vm.hostname = "vm1"
         node.vm.network "private_network", ip: "192.168.2.2"
		 node.vm.provider "virtualbox" do |vb|
            vb.name = "vm1"
            vb.memory = 512
            vb.cpus = 1
            vb.gui = false
         end
      end
      
      config.vm.define "vm2" do |node|
         node.vm.hostname = "vm2"
         node.vm.network "private_network", ip: "192.168.3.2"
         node.vm.provider "virtualbox" do |vb|
            vb.name = "vm2"
            vb.memory = 512
            vb.cpus = 1
            vb.gui = false
         end
      end
end
